### ISSUE TITLE
Update README with installation instructions

### ISSUE THREAD

**Issue by TheDevilOnLine** [BitBagCommerce/SyliusBonusPointsPlugin#1]
Please replace the default readme with actual installation instructions!

**Comment by romainguerrero** [comment]
up

**Comment by tbuczen** [comment]
Hey @TheDevilOnLine plugin is currently being updated to Sylius 1.9 along with the Readme file.

**Comment by KrisFlorq** [comment]
https://github.com/BitBagCommerce/SyliusBonusPointsPlugin/releases/tag/v1.0.0 issue resolved in this release.
