### ISSUE TITLE
The entity-class BitBag\SyliusBonusPointsPlugin\Entity\BonusPointsStrategyRule mapping is invalid

### ISSUE THREAD

**Issue by romainguerrero** [BitBagCommerce/SyliusBonusPointsPlugin#2]
Hello,

Thank you for your work on this plugin.
We installed it on our Sylius project, but when we want to validate the mapping using the `bin/console doctrine:schema:validate` command we have the following issue that we can't understand :
```
Mapping
-------

 [FAIL] The entity-class BitBag\SyliusBonusPointsPlugin\Entity\BonusPointsStrategyRule mapping is invalid:
 * The association BitBag\SyliusBonusPointsPlugin\Entity\BonusPointsStrategyRule#bonusPointsStrategy refers to the inverse side field BitBag\SyliusBonusPointsPlugin\Entity\BonusPointsStrategy#rules which does not exist.
```

Is there something we have to configure or implement somewhere to avoid this issue ?

**Comment by tbuczen** [comment]
@romainguerrero Is this still happening for You in latest version ? Mappings seems to be correct and I cannot reproduce the issue.

**Comment by romainguerrero** [comment]
It seem OK now. Thank you for your work !
