### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by chyzas** [BitBagCommerce/SyliusBonusPointsPlugin#28]
When do you plan to do a new release to add latest changes to the master (and new version tag)?

**Comment by KrisFlorq** [comment]
Hi @chyzas ! Thank You for reaching out to us, maybe it is the time to undust this plugin a litle-bit... We will put our focus on it, so that in the next weeks this issue can be closed by the new release ;)

**Comment by KrisFlorq** [comment]
https://github.com/BitBagCommerce/SyliusBonusPointsPlugin/releases/tag/v1.0.0 issue resolved in this release.
