### ISSUE TITLE
Bonus points calculation is off in BitBag\SyliusBonusPointsPlugin\Resolver\BonusPointsResolver 

### ISSUE THREAD

**Issue by AlexPosada** [BitBagCommerce/SyliusBonusPointsPlugin#3]
Hello,

First of all I wanted to thank you for your very useful bundle. However, I have spotted what seems to be a mistake in the calculation of bonus points (method `resolveBonusPoints` in `BitBag\SyliusBonusPointsPlugin\Resolver\BonusPointsResolver`). 
This method basically adds up all the non-expired customer bonus points, then deduces used bonus points and returns the result. The calculation does a general balance between available points and used points when it should take into account that available points evolve over time. Here is an example: 

![Capture d’écran 2020-06-18 à 16 34 50](https://user-images.githubusercontent.com/40704758/85035697-c14b6f80-b183-11ea-8caa-e2798919d7f3.png)

- First order: January 1st, 8 points expiring April 2nd.
- Second order: April 1st, 8 points expiring July 1st.
- Thirst order: April 1st, **-8 points**.
- Fourth order: June 1st, 4 points expiring December 18th.

When I do the balance on June 18th  I get:

![Capture d’écran 2020-06-18 à 16 51 31](https://user-images.githubusercontent.com/40704758/85036700-bcd38680-b184-11ea-9be4-6ac6c77eb1fe.png)

I have 4 points instead of 12 because the calculation discarded the 8 points now expired and normally used with the client's third order.

Furthermore, I see another problem as time goes on: More points (used or not) will go expired making the pool of used bonus points bigger and bigger while the pool of bonus points will decrease, making the ability of a customer to generate bonus points harder and harder as time passes.

To correct this, the calculation should go through the customer bonus points history and for each event (addition or subtraction of points) check available points at the time and subtract, if necessary, first from the most ancients valid points.

**Comment by tbuczen** [comment]
Hello @AlexPosada, thanks for Your feedback with PR, this is going to be reviewed in the upcoming plugin updated.

**Comment by KrisFlorq** [comment]
https://github.com/BitBagCommerce/SyliusBonusPointsPlugin/releases/tag/v1.0.0 issue resolved in this release.
