### ISSUE TITLE
Including bonus points / discount amount to product page & cart

### ISSUE THREAD

**Issue by JeroenVeldmeijer** [BitBagCommerce/SyliusBonusPointsPlugin#37]
We would like to set up the following situations. We want to ...

- show visitors the number of bonus points the visitor would collect if the product would be purchased. Same for the discount. How much discount would the visitor get, after buying the product.

- show visitor the number of bonus points one collects if the total cart would be purchased and the total discount the visitor is entitled to, after completing the purchase. 

- show to a signed in user - in their account - the total number of collected bonus points and to which discount amount this entitles to. 

Can you please help / suggest if there are any predefined parameters we can use? If not, can you make suggestions how we can make this work?

**Comment by JeroenVeldmeijer** [comment]
Hello,
We really would like to move on with this issue. Can someone help?
Best wishes,
Jeroen

**Comment by MacBalc** [comment]
Hello @JeroenVeldmeijer , seems like showing current user points may be done by extending templates and utilizing **CustomerBonusPoints** entity. As for calculating possibly earned bonus points i would suggest using built in calculators logic, as calculators seems to be non persistent. If I could be of any help, feel free to reopen.
